# Notebook 1 - Data Wrangling

## 1.1 Intro & Problem identification

[KAggle Intro](https://www.kaggle.com/sohier/competition-api-detailed-introduction)

I need to set up the environment and use the **riideducation** Python module.
 

## 1.2 Imports

In [1]:
import os
import pandas as pd
import datatable as dt 

## 1.3 Data Collection

In [2]:
# To reduce loading time I am using datatable library for the train set
%%time

data = dt.fread("E:\Springboard\GitHub/riiid_capstone/data/raw/train.csv")

print("Train size:", data.shape)


Train size: (101230332, 10)
Wall time: 54.9 s


In [26]:
%%time

lectures = pd.read_csv('E:\Springboard\GitHub/riiid_capstone/data/raw/lectures.csv')
questions = pd.read_csv('E:\Springboard\GitHub/riiid_capstone/data/raw/questions.csv')
print("Lectures size:", lectures.shape,'\nQuestions size:', questions.shape)

Lectures size: (418, 4) 
Questions size: (13523, 5)
Wall time: 18.9 ms


In [6]:
# Transfmoring the train set to pandas DF
%%time

data_pd = data.to_pandas()

Wall time: 25.4 s


In [7]:
data_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101230332 entries, 0 to 101230331
Data columns (total 10 columns):
 #   Column                          Dtype  
---  ------                          -----  
 0   row_id                          int32  
 1   timestamp                       int64  
 2   user_id                         int32  
 3   content_id                      int32  
 4   content_type_id                 bool   
 5   task_container_id               int32  
 6   user_answer                     int32  
 7   answered_correctly              int32  
 8   prior_question_elapsed_time     float64
 9   prior_question_had_explanation  object 
dtypes: bool(1), float64(1), int32(6), int64(1), object(1)
memory usage: 4.6+ GB


In [10]:
# Checking memory usage from main DF
data_pd.memory_usage(deep=True)

Index                                    128
row_id                             404921328
timestamp                          809842656
user_id                            404921328
content_id                         404921328
content_type_id                    101230332
task_container_id                  404921328
user_answer                        404921328
answered_correctly                 404921328
prior_question_elapsed_time        809842656
prior_question_had_explanation    3598112864
dtype: int64

In [11]:
# Changing 'prior_question_had_explanation' column type to Boolean
data_pd['prior_question_had_explanation'] = data_pd['prior_question_had_explanation'].astype('boolean')

data_pd.memory_usage(deep=True)

Index                                   128
row_id                            404921328
timestamp                         809842656
user_id                           404921328
content_id                        404921328
content_type_id                   101230332
task_container_id                 404921328
user_answer                       404921328
answered_correctly                404921328
prior_question_elapsed_time       809842656
prior_question_had_explanation    202460664
dtype: int64

## 1.4 Data Organization

For this project I'll be using the CookieCutter project organization, all uploaded to my Github repository.
I will submit a notebook for each of the steps in the Data Science Method:
1. Data Wrangling
2. EDA
3. Pre-processing and Training Data Development
4. Modeling

Other useful information will be found in the folowing folders: data, models, reports, src.


## 1.5 Data Definition

In the **Data Wrangling** and **EDA** steps we will be working with 3 datasets:

### 1.5.1 Train set

1. **Features**
    - **row_id**: (int64) ID code for the row.
    - **timestamp**: (int64) the time in milliseconds between this user interaction and the first event completion from that user.
    - **user_id**: (int32) ID code for the user.
    - **content_id**: (int16) ID code for the user interaction
    - **content_type_id**: (int8) 0 if the event was a question being posed to the user, 1 if the event was the user watching a lecture.
    - **task_container_id**: (int16) Id code for the batch of questions or lectures. For example, a user might see three questions in a row before seeing the explanations for any of them. Those three would all share a task_container_id.
    - **user_answer**: (int8) the user's answer to the question, if any. Read -1 as null, for lectures.
    - **answered_correctly**: (int8) if the user responded correctly. Read -1 as null, for lectures.
    - **prior_question_elapsed_time**: (float32) The average time in milliseconds it took a user to answer each question in the previous question bundle, ignoring any lectures in between. Is null for a user's first question bundle or lecture. Note that the time is the average time a user took to solve each question in the previous bundle.
    - **prior_question_had_explanation**: (bool) Whether or not the user saw an explanation and the correct response(s) after answering the previous question bundle, ignoring any lectures in between. The value is shared across a single question bundle, and is null for a user's first question bundle or lecture. Typically the first several questions a user sees were part of an onboarding diagnostic test where they did not get any feedback.

In [14]:
train = data_pd
train.describe()

row_id     timestamp       user_id    content_id  \
count  1.012303e+08  1.012303e+08  1.012303e+08  1.012303e+08   
mean   5.061517e+07  7.703644e+09  1.076732e+09  5.219605e+03   
std    2.922268e+07  1.159266e+10  6.197163e+08  3.866359e+03   
min    0.000000e+00  0.000000e+00  1.150000e+02  0.000000e+00   
25%    2.530758e+07  5.243436e+08  5.408116e+08  2.063000e+03   
50%    5.061517e+07  2.674234e+09  1.071781e+09  5.026000e+03   
75%    7.592275e+07  9.924551e+09  1.615742e+09  7.425000e+03   
max    1.012303e+08  8.742577e+10  2.147483e+09  3.273600e+04   

       task_container_id   user_answer  answered_correctly  \
count       1.012303e+08  1.012303e+08        1.012303e+08   
mean        9.040624e+02  1.376123e+00        6.251644e-01   
std         1.358302e+03  1.192896e+00        5.225307e-01   
min         0.000000e+00 -1.000000e+00       -1.000000e+00   
25%         1.040000e+02  0.000000e+00        0.000000e+00   
50%         3.820000e+02  1.000000e+00        1.000000e+00   
75%         1.094000e+03  3.000000e+00        1.000000e+00   
max         9.999000e+03  3.000000e+00        1.000000e+00   

       prior_question_elapsed_time  
count                 9.887879e+07  
mean                  2.542381e+04  
std                   1.994815e+04  
min                   0.000000e+00  
25%                   1.600000e+04  
50%                   2.100000e+04  
75%                   2.966600e+04  
max                   3.000000e+05

In [17]:
train.head(10)

row_id  timestamp  user_id  content_id  content_type_id  task_container_id  \
0       0          0      115        5692            False                  1   
1       1      56943      115        5716            False                  2   
2       2     118363      115         128            False                  0   
3       3     131167      115        7860            False                  3   
4       4     137965      115        7922            False                  4   
5       5     157063      115         156            False                  5   
6       6     176092      115          51            False                  6   
7       7     194190      115          50            False                  7   
8       8     212463      115        7896            False                  8   
9       9     230983      115        7863            False                  9   

   user_answer  answered_correctly  prior_question_elapsed_time  \
0            3                   1                          NaN   
1            2                   1                      37000.0   
2            0                   1                      55000.0   
3            0                   1                      19000.0   
4            1                   1                      11000.0   
5            2                   1                       5000.0   
6            0                   1                      17000.0   
7            3                   1                      17000.0   
8            2                   1                      16000.0   
9            0                   1                      16000.0   

   prior_question_had_explanation  
0                            <NA>  
1                           False  
2                           False  
3                           False  
4                           False  
5                           False  
6                           False  
7                           False  
8                           False  
9                           False

**2. Calculating the percentage of missing values per feature**

In [31]:
missing = pd.concat([train.isnull().sum(), 100 * train.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count')

count         %
row_id                                0  0.000000
timestamp                             0  0.000000
user_id                               0  0.000000
content_id                            0  0.000000
content_type_id                       0  0.000000
task_container_id                     0  0.000000
user_answer                           0  0.000000
answered_correctly                    0  0.000000
prior_question_had_explanation   392506  0.387736
prior_question_elapsed_time     2351538  2.322958

We have 392,506 interactions without prior_question_had_explanation	and 2,351,538 without prior_question_elapsed_time

### 1.5.2 Questions Set

**1.Features**

- **question_id**: foreign key for the train/test content_id column, when the content type is question (0).

- **bundle_id**: code for which questions are served together.

- **correct_answer**: the answer to the question. Can be compared with the train user_answer column to check if the user was right.

- **part**: the relevant section of the TOEIC test.

- **tags** : one or more detailed tag codes for the question. The meaning of the tags will not be provided, but these codes are sufficient for clustering the questions together.

In [18]:
print("\n Questions dataset")
questions.info()


 Questions dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13523 entries, 0 to 13522
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   question_id     13523 non-null  int64 
 1   bundle_id       13523 non-null  int64 
 2   correct_answer  13523 non-null  int64 
 3   part            13523 non-null  int64 
 4   tags            13522 non-null  object
dtypes: int64(4), object(1)
memory usage: 528.4+ KB


In [20]:
questions.describe()

question_id     bundle_id  correct_answer          part
count  13523.00000  13523.000000    13523.000000  13523.000000
mean    6761.00000   6760.510907        1.455298      4.264956
std     3903.89818   3903.857783        1.149707      1.652553
min        0.00000      0.000000        0.000000      1.000000
25%     3380.50000   3379.500000        0.000000      3.000000
50%     6761.00000   6761.000000        1.000000      5.000000
75%    10141.50000  10140.000000        3.000000      5.000000
max    13522.00000  13522.000000        3.000000      7.000000

In [25]:
questions.head(10)

question_id  bundle_id  correct_answer  part            tags
0            0          0               0     1   51 131 162 38
1            1          1               1     1       131 36 81
2            2          2               0     1  131 101 162 92
3            3          3               0     1  131 149 162 29
4            4          4               3     1    131 5 162 38
5            5          5               2     1  131 149 162 81
6            6          6               2     1    10 94 162 92
7            7          7               0     1   61 110 162 29
8            8          8               3     1   131 13 162 92
9            9          9               3     1       10 164 81

**2. Calculating the percentage of missing values per feature**

In [28]:
missing = pd.concat([questions.isnull().sum(), 100 * questions.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count')

count         %
question_id         0  0.000000
bundle_id           0  0.000000
correct_answer      0  0.000000
part                0  0.000000
tags                1  0.007395

There is one question that has no tags

In [30]:
questions[questions.tags.isnull()] ## Question 10033

question_id  bundle_id  correct_answer  part tags
10033        10033      10033               2     6  NaN

### 1.5.3 Lectures Set

**1.Features**

- **lecture_id**: foreign key for the train/test content_id column, when the content type is lecture (1).

- **part**: top level category code for the lecture.

- **tag**: one tag codes for the lecture. The meaning of the tags will not be provided, but these codes are sufficient for clustering the lectures together.

- **type_of**: brief description of the core purpose of the lecture

In [22]:
print("\n Lectures dataset")
lectures.info()


 Lectures dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   lecture_id  418 non-null    int64 
 1   tag         418 non-null    int64 
 2   part        418 non-null    int64 
 3   type_of     418 non-null    object
dtypes: int64(3), object(1)
memory usage: 13.2+ KB


In [23]:
lectures.describe()

lecture_id         tag        part
count    418.000000  418.000000  418.000000
mean   16983.401914   94.480861    4.267943
std     9426.164660   53.586487    1.872424
min       89.000000    0.000000    1.000000
25%     9026.250000   50.250000    2.000000
50%    17161.500000   94.500000    5.000000
75%    24906.250000  140.000000    6.000000
max    32736.000000  187.000000    7.000000

In [24]:
lectures.head(10)

lecture_id  tag  part           type_of
0          89  159     5           concept
1         100   70     1           concept
2         185   45     6           concept
3         192   79     5  solving question
4         317  156     5  solving question
5         335  114     2           concept
6         484  179     5           concept
7         641  134     6  solving question
8         761   93     1           concept
9         814   80     5  solving question

**2. Calculating the percentage of missing values per feature**

In [27]:
missing = pd.concat([lectures.isnull().sum(), 100 * lectures.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count')

count    %
lecture_id      0  0.0
tag             0  0.0
part            0  0.0
type_of         0  0.0

There is no feature missing from Lectures

## 1.6 Data Cleaning